version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule: 
    interval: daily
  open-pull-requests-limit: 10
